### PR TITLE
457 adjust manager add book manually UI

### PR DESCRIPTION
**Pull request by mabrur-h**

### CODE REVIEW

**Comment by Chichmarin17** [comment]
Doesn't match the design https://www.figma.com/file/pxj9Hhk5AdOxXWJP0dq4gT/Library-App-Spec?node-id=4760%3A10249 (different size and view of `upload` image as well as position of the bottom buttons). Also, if you provided some changes to the text context, add i18next internalization language support (`localization` folder), but check if there is such text exists in the first place. 
Add base test cases for the changed files it there are not such
Also, try to add more description to the pull request with `Closes #issue_number` (see https://github.com/iTechLibrary/mimir/pull/455)

**Comment by mabrur-h** [comment]
Now I'm going to write tests for components

**Comment by mabrur-h** [comment]
image
image
Mobile Version
image
Desktop Version

**Review by Chichmarin17 — CHANGES_REQUESTED** [review]
Looks fine for user ui, but you should check this page as manager (see https://www.figma.com/file/pxj9Hhk5AdOxXWJP0dq4gT/Library-App-Spec?node-id=4889%3A16286). Adjust bottom buttons in manager flow to match design.
image

To change your role to `manager`, find your user in `person` table (mimir database), and change your role to be able to look at the page as a manager

**Pull request closed without merging**
