### PR TITLE
edit background patterns

### PR DESCRIPTION
**Pull request by mabrur-h**

### CODE REVIEW

**Comment by Chichmarin17** [comment]
Looks ok for me. What do you think @unrealsolve? Image size increased on 30kb

**Review by Chichmarin17 — APPROVED** [review]

**Review by unrealsolver — CHANGES_REQUESTED** [review]
1. Please add screenshots for mobile and desktop versions
2. Don't use the same names for files (startpage_pattern is indistinguishable from startpage-pattern)

**Comment by mabrur-h** [comment]
> * Please add screenshots for mobile and desktop versions

@unrealsolver What screenshots are you asking about and where should I add them?

**Comment by Chichmarin17** [comment]
Make screenshots of the start page for mobile (~420px) and desktop versions and put it into the PRs description

**Comment by mabrur-h** [comment]
Mobile version
image
image
Desktop version
image

**Comment by mabrur-h** [comment]
Now I'm going to write tests for components.

**Comment by mabrur-h** [comment]
✅Changed name of the file

**Comment by mabrur-h** [comment]
Mobile Version
image
Desktop Version
image

**Review by unrealsolver — APPROVED** [review]

**Pull request merged**
